{{- if .Values.privateRegistry.registrySecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.privateRegistry.registrySecret }}
  namespace: {{ include "release_namespace" . }}
  labels: {{- include "longhorn.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "secret" . }}
{{- end }}