name: "[Issue Management] Close Stale Issues and PRs"

on:
  workflow_call:
  workflow_dispatch:
  schedule:
  - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v9
      with:
        stale-issue-message: 'This issue is stale because it has been open for 30 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
        stale-pr-message: 'This PR is stale because it has been open for 30 days with no activity. Remove stale label or comment or this will be closed in 10 days.'
        close-issue-message: 'This issue was closed because it has been stalled for 5 days with no activity.'
        close-pr-message: 'This PR was closed because it has been stalled for 5 days with no activity.'
        close-issue-label: 'wontfix'
        days-before-stale: 30
        days-before-pr-stale: 30
        days-before-close: 5
        days-before-pr-close: 5
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        exempt-all-assignees: true
        exempt-issue-labels: 'kind/improvement,kind/feature,kind/test,investigation-needed'
        exempt-draft-pr: true
        exempt-all-milestones: true
